ENROOT_RUNTIME_PATH /run/enroot/user-$(id -u)
ENROOT_CACHE_PATH   /share/enroot-cache/group-$(id -g)
ENROOT_DATA_PATH    /scratch/enroot-data/user-$(id -u)
ENROOT_MOUNT_HOME   n
ENROOT_RESTRICT_DEV y
ENROOT_ROOTFS_WRITABLE y
ENROOT_REMAP_ROOT   n
